// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vehicle_Management.Infrastructure;

#nullable disable

namespace Vehicle_Management.Infrastructure.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20260911201142_CientRequestAdded")]
    partial class CientRequestAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Vehicle_Management.Domain.Aggregates.BookingAggregate.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingStatus")
                        .HasColumnType("int");

                    b.Property<Guid>("Employee_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Vehicle_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("_fuelpolicy")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("timeframe")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Vehicle_Management.Domain.Aggregates.VehicleAggregate.Vehicle", b =>
                {
                    b.Property<string>("License_Plate")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Odometer")
                        .HasColumnType("int");

                    b.Property<int>("_classification")
                        .HasColumnType("int");

                    b.Property<int>("_status")
                        .HasColumnType("int");

                    b.HasKey("License_Plate");

                    b.HasIndex("License_Plate")
                        .IsUnique();

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("Vehicle_Management.Domain.SeedWork.ClientRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ClientRequests");
                });

            modelBuilder.Entity("Vehicle_Management.Domain.Aggregates.BookingAggregate.Booking", b =>
                {
                    b.OwnsOne("Vehicle_Management.Domain.Aggregates.BookingAggregate.TripWindow", "_tripwindow", b1 =>
                        {
                            b1.Property<int>("BookingId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("End")
                                .HasColumnType("datetime2")
                                .HasColumnName("TripEnd");

                            b1.Property<DateTime>("Start")
                                .HasColumnType("datetime2")
                                .HasColumnName("TripStart");

                            b1.HasKey("BookingId");

                            b1.ToTable("Bookings");

                            b1.WithOwner()
                                .HasForeignKey("BookingId");
                        });

                    b.Navigation("_tripwindow")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
